openapi: "3.0.1"
info:
  version: "1"
  title: "Helloworld documentation"

paths:

  /helloworld:
    post:
      summary: "Create a Helloworld translation"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Helloworld"
      responses:
        201:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Helloworld"

  /helloworld/{uuid}:
    get:
      summary: "Find helloworld translation by uuid"
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Helloworld"

components:
  schemas:
    Helloworld:
      type: object
      properties:
        language:
          type: string
        value:
          type: string